# src/app/models/caption.py
"""
Caption Model
Represents YouTube video captions/subtitles with multilingual support
"""

from datetime import datetime
from typing import Optional, List, TYPE_CHECKING
from enum import Enum
from sqlalchemy import (
    Column,
    String,
    Integer,
    BigInteger,
    DateTime,
    Text,
    Boolean,
    Float,
    ForeignKey,
    Index,
    JSON,
)
from sqlalchemy.orm import relationship

from src.infrastructure.database.connection import Base

if TYPE_CHECKING:
    from .video import Video


class CaptionFormat(str, Enum):
    """Caption format types"""
    SRT = "srt"
    VTT = "vtt"
    JSON = "json"
    TXT = "txt"


class CaptionType(str, Enum):
    """Caption source type"""
    MANUAL = "manual"       # Manually uploaded by creator
    AUTO = "auto"           # Auto-generated by YouTube
    COMMUNITY = "community" # Community contributed


class Caption(Base):
    """
    YouTube Caption/Subtitle entity

    Stores caption metadata and content for video subtitles
    """

    __tablename__ = "captions"
    __table_args__ = {"extend_existing": True}

    # Primary Key
    id = Column(String(100), primary_key=True, comment="Caption track ID")

    # Foreign Key
    video_id = Column(
        String(50),
        ForeignKey("videos.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="Associated video ID",
    )

    # Caption Metadata
    language_code = Column(
        String(20), nullable=False, index=True, comment="Language code (e.g., 'en', 'zh-TW')"
    )
    language_name = Column(String(100), comment="Language display name")
    caption_type = Column(
        String(20), default=CaptionType.AUTO.value, comment="Caption type (manual/auto/community)"
    )
    is_translatable = Column(Boolean, default=False, comment="Can be auto-translated")
    is_auto_synced = Column(Boolean, default=False, comment="Auto-synced timing")

    # Content
    content = Column(Text, comment="Full caption text content")
    content_json = Column(JSON, comment="Structured caption with timestamps")

    # Statistics
    duration_seconds = Column(Float, comment="Total duration in seconds")
    word_count = Column(Integer, default=0, comment="Total word count")
    segment_count = Column(Integer, default=0, comment="Number of caption segments")

    # Processing Status
    is_processed = Column(Boolean, default=False, index=True, comment="Processing complete")
    processing_error = Column(Text, comment="Error message if processing failed")

    # Timestamps
    fetched_at = Column(
        DateTime, nullable=False, default=datetime.utcnow, comment="When caption was fetched"
    )
    created_at = Column(
        DateTime, nullable=False, default=datetime.utcnow, comment="Record creation"
    )
    updated_at = Column(
        DateTime,
        nullable=False,
        default=datetime.utcnow,
        onupdate=datetime.utcnow,
        comment="Last update timestamp",
    )

    # Relationships
    video = relationship("Video", back_populates="captions")

    def __repr__(self):
        return f"<Caption(id={self.id}, video_id={self.video_id}, language={self.language_code})>"

    def to_dict(self) -> dict:
        """Convert model to dictionary"""
        return {
            "id": self.id,
            "video_id": self.video_id,
            "language_code": self.language_code,
            "language_name": self.language_name,
            "caption_type": self.caption_type,
            "is_translatable": self.is_translatable,
            "word_count": self.word_count,
            "segment_count": self.segment_count,
            "duration_seconds": self.duration_seconds,
            "is_processed": self.is_processed,
            "fetched_at": self.fetched_at.isoformat() if self.fetched_at else None,
        }

    @property
    def full_text(self) -> str:
        """Get plain text content without timestamps"""
        if self.content:
            return self.content
        if self.content_json:
            return " ".join(seg.get("text", "") for seg in self.content_json)
        return ""


class CaptionSegment(Base):
    """
    Caption Segment entity

    Individual caption segments with timing information
    Useful for search and precise timestamp navigation
    """

    __tablename__ = "caption_segments"
    __table_args__ = {"extend_existing": True}

    # Primary Key
    id = Column(Integer, primary_key=True, autoincrement=True)

    # Foreign Keys
    caption_id = Column(
        String(100),
        ForeignKey("captions.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="Parent caption ID",
    )
    video_id = Column(
        String(50),
        ForeignKey("videos.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="Associated video ID",
    )

    # Timing
    start_time = Column(Float, nullable=False, comment="Start time in seconds")
    end_time = Column(Float, nullable=False, comment="End time in seconds")
    duration = Column(Float, comment="Segment duration in seconds")

    # Content
    text = Column(Text, nullable=False, comment="Segment text content")
    text_normalized = Column(Text, comment="Normalized text for search")

    # Segment index for ordering
    segment_index = Column(Integer, nullable=False, comment="Segment order index")

    # Timestamps
    created_at = Column(DateTime, nullable=False, default=datetime.utcnow)

    def __repr__(self):
        return f"<CaptionSegment(id={self.id}, start={self.start_time}, text={self.text[:30]}...)>"

    def to_dict(self) -> dict:
        """Convert to dictionary"""
        return {
            "id": self.id,
            "start_time": self.start_time,
            "end_time": self.end_time,
            "duration": self.duration,
            "text": self.text,
            "segment_index": self.segment_index,
        }


# Indexes for common queries
Index("idx_caption_video_language", Caption.video_id, Caption.language_code)
Index("idx_caption_processed", Caption.is_processed, Caption.created_at.desc())
Index("idx_segment_video_time", CaptionSegment.video_id, CaptionSegment.start_time)


__all__ = ["Caption", "CaptionSegment", "CaptionFormat", "CaptionType"]
